runtime: nodejs10
env: standard

# Option no longer possible at this time... boo.
#resources:
#  cpu: .5
#  memory_gb: 0.18
#  disk_size_gb: 10

env_variables:
    DB_USER: riatorre
    DB_PASS: SiD1475357
    DB_INSTANCE_NAME: cruzsafe:us-west2:cruzsafe-data
    DB_DATABASE: cruzsafe_main

beta_settings:
    cloud_sql_instances: cruzsafe:us-west2:cruzsafe-data
